lessons:
  outputs:
    dev:
      dataset: dbt_al
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: bigquery-479205
      threads: 60
      type: bigquery
  target: dev
